# Generated by Django 6.0.4 on 2026-04-30 20:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='etb_to_usd_rate',
            field=models.DecimalField(decimal_places=4, default=0.018, help_text='Exchange rate: 1 ETB = X USD (e.g., 0.0180)', max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
