# Generated by Django 4.2 on 2026-04-25 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('borrow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='borrowrecord',
            index=models.Index(fields=['user', 'status'], name='borrow_borr_user_id_aa94e5_idx'),
        ),
        migrations.AddIndex(
            model_name='borrowrecord',
            index=models.Index(fields=['book'], name='borrow_borr_book_id_5d6774_idx'),
        ),
        migrations.AddIndex(
            model_name='borrowrecord',
            index=models.Index(fields=['due_date'], name='borrow_borr_due_dat_a372cc_idx'),
        ),
    ]
