# Generated by Django 6.0.4 on 2026-04-26 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
        ('borrow', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='returned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returned_books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BookRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('issued', 'Issued')], default='pending', max_length=20)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_requests', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-request_date'],
            },
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='book_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrow_record', to='borrow.bookrequest'),
        ),
        migrations.AddIndex(
            model_name='bookrequest',
            index=models.Index(fields=['user', 'status'], name='borrow_book_user_id_591585_idx'),
        ),
        migrations.AddIndex(
            model_name='bookrequest',
            index=models.Index(fields=['book', 'status'], name='borrow_book_book_id_a94e0d_idx'),
        ),
        migrations.AddIndex(
            model_name='bookrequest',
            index=models.Index(fields=['status'], name='borrow_book_status_fd13fe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bookrequest',
            unique_together={('user', 'book', 'status')},
        ),
    ]
