# Generated by Django 6.0.4 on 2026-04-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0003_borrowrecord_issued_by_borrowrecord_returned_to_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookrequest',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready for Pickup'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
