# Generated by Django 6.0.4 on 2026-04-27 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(max_length=50)),
                ('notification_key', models.CharField(max_length=255)),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-read_at'],
                'indexes': [models.Index(fields=['user', 'notification_type'], name='users_notif_user_id_5f4a6a_idx'), models.Index(fields=['notification_key'], name='users_notif_notific_c9e977_idx')],
                'unique_together': {('user', 'notification_type', 'notification_key')},
            },
        ),
    ]
