# Generated by Django 6.0.4 on 2026-04-27 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_notificationread'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reading_badge',
            field=models.CharField(choices=[('reader', 'Reader'), ('book_lover', 'Book Lover'), ('avid_reader', 'Avid Reader')], default='reader', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_books_read',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('book_added', 'Book Added'), ('book_updated', 'Book Updated'), ('book_deleted', 'Book Deleted'), ('book_borrowed', 'Book Borrowed'), ('book_returned', 'Book Returned'), ('request_created', 'Request Created'), ('request_approved', 'Request Approved'), ('request_rejected', 'Request Rejected'), ('request_cancelled', 'Request Cancelled'), ('fine_paid', 'Fine Paid'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_role_changed', 'User Role Changed'), ('review_added', 'Review Added'), ('backup_created', 'Backup Created'), ('reminder_sent', 'Reminder Sent'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'action'], name='users_activ_user_id_0b9d76_idx'), models.Index(fields=['created_at'], name='users_activ_created_31380b_idx')],
            },
        ),
    ]
