# Generated by Django 6.0.4 on 2026-04-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_reading_badge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='max_books_allowed',
            field=models.IntegerField(default=5),
        ),
    ]
