# Generated by Django 6.0.4 on 2026-04-30 06:40

from django.db import migrations


def update_max_books_allowed(apps, schema_editor):
    """Update existing user profiles to have max_books_allowed = 5"""
    UserProfile = apps.get_model('users', 'UserProfile')
    # Update all profiles that have the old default of 3 to the new default of 5
    UserProfile.objects.filter(max_books_allowed=3).update(max_books_allowed=5)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_update_max_books_allowed'),
    ]

    operations = [
        migrations.RunPython(update_max_books_allowed, reverse_code=migrations.RunPython.noop),
    ]
