# Generated by Django 6.0.4 on 2026-04-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_update_existing_profiles_max_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='max_books_allowed',
            field=models.IntegerField(default=7),
        ),
    ]
