# Generated by Django 4.2 on 2026-04-25 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.category'),
        ),
        migrations.AddIndex(
            model_name='bookreview',
            index=models.Index(fields=['book', 'user'], name='books_bookr_book_id_cc2272_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bookreview',
            unique_together={('book', 'user')},
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['isbn'], name='books_book_isbn_54becd_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title'], name='books_book_title_d3218d_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['category'], name='books_book_categor_bb0287_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['available_copies'], name='books_book_availab_bb9890_idx'),
        ),
    ]
